"""Official Python SDK for Arena Hero."""

from importlib.metadata import version

from .actions import (
    Accepted,
    CancelMoveAction,
    CommandPlan,
    DepositAction,
    DropBeaconAction,
    HarvestAction,
    HealAction,
    MoveAction,
    PickupBeaconAction,
    RepairShieldAction,
    SelfDestructAction,
    ShootAction,
    SpawnAction,
    StartMoveAction,
    SweepAction,
    WaitAction,
)
from .async_client import AsyncArenaHeroClient, AsyncGameEvent
from .client import ArenaHeroClient, SyncGameEvent
from .config_overrides import (
    apply_config_overrides,
    load_config_overrides,
    overridden_decide_kwargs,
)
from .enums import (
    BeaconStatus,
    CommandSource,
    CoreState,
    Direction,
    HarvestSource,
    PlayerStatus,
    UnitType,
)
from .errors import (
    APIError,
    ArenaHeroError,
    AuthenticationError,
    ConfigurationError,
    InvalidActionError,
    PolicyViolationError,
    ProtocolError,
    TransportError,
    TurnClosedError,
)
from .geometry import Coordinate, Position
from .models import (
    ChampionBeacon,
    CoreResourceCapture,
    CoreView,
    HealingResult,
    PlayerState,
    Received,
    ResolutionEvent,
    TerrainView,
    Tick,
    UnitView,
)
from .rules import (
    CORE_RESOURCE_CAPACITY_PER_UNIT,
    CORE_RESOURCE_MINIMUM_CAPACITY,
    UNIT_BASE_COSTS,
    core_resource_capacity,
    unit_cost,
)
from .turn import AsyncTurn, Core, Ranger, Turn, Unit, Vanguard, Worker

__version__ = version("arena-hero")

__all__ = [
    "CORE_RESOURCE_CAPACITY_PER_UNIT",
    "CORE_RESOURCE_MINIMUM_CAPACITY",
    "UNIT_BASE_COSTS",
    "APIError",
    "Accepted",
    "ArenaHeroClient",
    "ArenaHeroError",
    "AsyncArenaHeroClient",
    "AsyncGameEvent",
    "AsyncTurn",
    "AuthenticationError",
    "BeaconStatus",
    "CancelMoveAction",
    "ChampionBeacon",
    "CommandPlan",
    "CommandSource",
    "ConfigurationError",
    "Coordinate",
    "Core",
    "CoreResourceCapture",
    "CoreState",
    "CoreView",
    "DepositAction",
    "Direction",
    "DropBeaconAction",
    "HarvestAction",
    "HarvestSource",
    "HealAction",
    "HealingResult",
    "InvalidActionError",
    "MoveAction",
    "PickupBeaconAction",
    "PlayerState",
    "PlayerStatus",
    "PolicyViolationError",
    "Position",
    "ProtocolError",
    "Ranger",
    "Received",
    "RepairShieldAction",
    "ResolutionEvent",
    "SelfDestructAction",
    "ShootAction",
    "SpawnAction",
    "StartMoveAction",
    "SweepAction",
    "SyncGameEvent",
    "TerrainView",
    "Tick",
    "TransportError",
    "Turn",
    "TurnClosedError",
    "Unit",
    "UnitType",
    "UnitView",
    "Vanguard",
    "WaitAction",
    "Worker",
    "__version__",
    "apply_config_overrides",
    "core_resource_capacity",
    "load_config_overrides",
    "overridden_decide_kwargs",
    "unit_cost",
]
