"""Official Python SDK for Arena Hero."""

from importlib.metadata import version

from .actions import (
    Accepted,
    CancelMoveAction,
    CommandPlan,
    DepositAction,
    DropBeaconAction,
    HarvestAction,
    MoveAction,
    PickupBeaconAction,
    RepairShieldAction,
    SelfDestructAction,
    ShootAction,
    SpawnAction,
    StartMoveAction,
    SweepAction,
    WaitAction,
)
from .async_client import AsyncArenaHeroClient, AsyncGameEvent
from .client import ArenaHeroClient, SyncGameEvent
from .enums import (
    BeaconStatus,
    CommandSource,
    CoreState,
    Direction,
    PlayerStatus,
    UnitType,
)
from .errors import (
    APIError,
    ArenaHeroError,
    AuthenticationError,
    ConfigurationError,
    InvalidActionError,
    PolicyViolationError,
    ProtocolError,
    TransportError,
    TurnClosedError,
)
from .geometry import Coordinate, Position
from .models import (
    ChampionBeacon,
    CoreView,
    PlayerState,
    Received,
    ResolutionEvent,
    TerrainView,
    Tick,
    UnitView,
)
from .turn import AsyncTurn, Core, Ranger, Turn, Unit, Vanguard, Worker

__version__ = version("arena-hero")

__all__ = [
    "APIError",
    "Accepted",
    "ArenaHeroClient",
    "ArenaHeroError",
    "AsyncArenaHeroClient",
    "AsyncGameEvent",
    "AsyncTurn",
    "AuthenticationError",
    "BeaconStatus",
    "CancelMoveAction",
    "ChampionBeacon",
    "CommandPlan",
    "CommandSource",
    "ConfigurationError",
    "Coordinate",
    "Core",
    "CoreState",
    "CoreView",
    "DepositAction",
    "Direction",
    "DropBeaconAction",
    "HarvestAction",
    "InvalidActionError",
    "MoveAction",
    "PickupBeaconAction",
    "PlayerState",
    "PlayerStatus",
    "PolicyViolationError",
    "Position",
    "ProtocolError",
    "Ranger",
    "Received",
    "RepairShieldAction",
    "ResolutionEvent",
    "SelfDestructAction",
    "ShootAction",
    "SpawnAction",
    "StartMoveAction",
    "SweepAction",
    "SyncGameEvent",
    "TerrainView",
    "Tick",
    "TransportError",
    "Turn",
    "TurnClosedError",
    "Unit",
    "UnitType",
    "UnitView",
    "Vanguard",
    "WaitAction",
    "Worker",
    "__version__",
]
